name = "ContextualBandits"
uuid = "36acd394-f996-4ca3-84ce-f99eafba1aa8"
authors = ["Douglas Corbin <dfcorbin98@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.4.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
